### ISSUE TITLE
Which download option to select for free version?

### ISSUE THREAD

**Issue by OscarVanL** [Ontotext-AD/graphdb-docker#18]
Hi,

I'm following the instructions to install the free edition. I've registered and been given several download options in the email:
**Download available for Windows, Mac, deb based Linux, rpm based Linux**

The instructions on this repo simply say:
_Register on the Ontotext website for the GraphDB Free edition. Download the zip file and place it in the free-edition subdirectory_

Further guidance on which distribution to use would be helpful :)

Thanks

**Comment by nikolaykolev** [comment]
Hi,
You should use the OS independent distribution. 
1. Checkout the repository
2. Place the zip file that you've downloaded in the folder free-edition
3. While in the main directory execute "make free VERSION=9.6.0" assuming you've downloaded version 9.6.0

**Comment by OscarVanL** [comment]
Thanks :) That worked.
