### ISSUE TITLE
Unable to run the docker on the linux server 

### ISSUE THREAD

**Issue by Gautamshahi** [Ontotext-AD/graphdb-docker#25]
Hi,

I am trying to run the Graphhdb over my server using the command wget 

but I am getting the error ERROR 406: (no description). Could you please help me to run the graphdb?

![image](https://user-images.githubusercontent.com/3966230/151155503-ef577681-c17e-4d9d-be59-e8f7184b3f36.png)

Also, how could I add my own RDF files and browse the data?

**Comment by nikolaykolev** [comment]
Hi, you can't use wget like this. It's used for file downloads mainly. If you wish to call any of the GraphDB endpoints you can use curl, but it's easier to learn how GraphDB works by using the Workbench by visiting http://localhost:7200 in your browser and also read GraphDB's documentation.
