### ISSUE TITLE
ADD failed

### ISSUE THREAD

**Issue by munim90** [Ontotext-AD/graphdb-docker#26]
Facing the following error while building the docker image:

```
ADD failed: file not found in build context or excluded by .dockerignore: stat graphdb-free-9.3.0-dist.zip: file does not exist
ERROR: Service 'graphdb' failed to build : Build failed
```

From where I can find the graphdb free zip/deb file?

**Comment by yaskoo** [comment]
you need to register [here](https://www.ontotext.com/products/graphdb/graphdb-free/?ref=menu) to get a download link.
