### ISSUE TITLE
Default tag `latest` not available

### ISSUE THREAD

**Issue by mamachanko** [Ontotext-AD/graphdb-docker#4]
Currently, no image is tagged with `latest` at [Docker Hub](https://hub.docker.com/r/ontotext/graphdb/tags/)

```shell
~ » docker pull ontotext/graphdb
Using default tag: latest
Error response from daemon: manifest for ontotext/graphdb:latest not found
```

It's what people run by default even if running with a specific tag works, e.g.
```shell
~ » docker run ontotext/graphdb:8.5.0-se
Unable to find image 'ontotext/graphdb:8.5.0-se' locally
8.5.0-se: Pulling from ontotext/graphdb
6d827a3ef358: Pull complete
...
```

**Comment by Vishalckc** [comment]
Similar Issue while pulling Docker images for the free version-
docker run -p 127.0.0.1:7200:7200 --name graphdb-instance-name -t ontotext/graphdb:tag
Unable to find image 'ontotext/graphdb:tag' locally
docker: Error response from daemon: manifest for ontotext/graphdb:tag not found: manifest unknown: manifest unknown.
See 'docker run --help'.
vishalckc@vishalckc-Virtua

**Comment by nikolaykolev** [comment]
the missing 'latest' tag is intentional
