### ISSUE TITLE
Publish preload image

### ISSUE THREAD

**Issue by ThomasThelen** [Ontotext-AD/graphdb-docker#46]
It would be nice not having to build the preload image and instead just pull it from dockerhub. This would allow us to have a streamlined deployment, only pulling from dockerhub and not needing to git clone this repo, making sure that it's up to date, etc.

**Comment by yaskoo** [comment]
The `importrdf` tool is part of the GraphDB distribution, so it's included in the docker image. You can do the following:
```
docker container run --rm -it \
	-v $PWD/preload:/preload \
	--entrypoint /opt/graphdb/dist/bin/importrdf \
	ontotext/graphdb:10.6.2 -Dgraphdb.home=/opt/graphdb/home preload -c /preload/graphdb-repo.ttl /preload/import/test.nt
```

Note that, since we're overriding the default `CMD`, we need to provide `-Dgraphdb.home=/opt/graphdb/home`.
