### ISSUE TITLE
Creating a repo does not work anymore from API because `Unsupported repository type: graphdb:SailRepository`

### ISSUE THREAD

**Issue by vemonet** [Ontotext-AD/graphdb-docker#51]
Hi. I am trying to create a repo using a repo-config.ttl file. It was working in the past, but today it is not working and showing an error that does not make any sense

The error is:

```
{"message":"Error processing request (Unsupported repository type: graphdb:SailRepository)."}
```

I am using `ontotext/graphdb:9.11.7-se` docker image (latest `se` images as of today)

I am using the default config given here: https://graphdb.ontotext.com/documentation/10.7/manage-repos-with-restapi.html

```turtle
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>.
@prefix rep: <http://www.openrdf.org/config/repository#>.
@prefix sr: <http://www.openrdf.org/config/repository/sail#>.
@prefix sail: <http://www.openrdf.org/config/sail#>.
@prefix graphdb: <http://www.ontotext.com/config/graphdb#>.

[] a rep:Repository ;
    rep:repositoryID "repo" ;
    rdfs:label "Sample repository TTL file." ;
    rep:repositoryImpl [
        rep:repositoryType "graphdb:SailRepository" ;
        sr:sailImpl [
            sail:sailType "graphdb:Sail" ;

            graphdb:read-only "false" ;

            # Inference and Validation
            graphdb:ruleset "rdfsplus-optimized" ;
            graphdb:disable-sameAs "true" ;
            graphdb:check-for-inconsistencies "false" ;

            # Indexing
            graphdb:entity-id-size "32" ;
            graphdb:enable-context-index "false" ;
            graphdb:enablePredicateList "true" ;
            graphdb:enable-fts-index "false" ;
            graphdb:fts-indexes ("default" "iri") ;
            graphdb:fts-string-literals-index "default" ;
            graphdb:fts-iris-index "none" ;

            # Queries and Updates
            graphdb:query-timeout "0" ;
            graphdb:throw-QueryEvaluationException-on-timeout "false" ;
            graphdb:query-limit-results "0" ;

            # Settable in the file but otherwise hidden in the UI and in the RDF4J console
            graphdb:base-URL "http://example.org/owlim#" ;
            graphdb:defaultNS "" ;
            graphdb:imports "" ;
            graphdb:repository-type "file-repository" ;
            graphdb:storage-folder "storage" ;
            graphdb:entity-index-size "10000000" ;
            graphdb:in-memory-literal-properties "true" ;
            graphdb:enable-literal-index "true" ;
        ]
    ].
```

Python code used to send the request:

```python
import requests

with open("test/repo-config.ttl", "rb") as f:
    resp = requests.post(f"{base_url}/rest/repositories", files={'config': f})
```

How is it possible that GraphDB complains that `graphdb:SailRepository` is unsupported repository type? It has always been the default repo type.

@nikolaykolev

**Comment by vemonet** [comment]
It seems to be `graphdb:FreeSailRepository` apparently

**Comment by vemonet** [comment]
It does not work with `graphdb:FreeSailRepository` (which I found in older docs), we are getting this error message:

```
No software license was set. License can be set in one of the following ways (in order of preference):
- System or config property 'graphdb.license.file'
- File 'graphdb.license' in config directory (/opt/graphdb/home/conf)
- Set through Workbench or API
- Set via an external license provider
```

Quite crazy, not sure how GraphDB ends up throwing up this message... It would be quite easy to improve this error message to let the user know which repository types are available, just sayin'

Since the documentation seems to not be up to date on repositoryTypes, I went to the web UI, created a repository through the UI, which worked, and checked the network call that was done to http://localhost:7200/rest/repositories

And found a json, which specifies `"repositoryType":{"name":"repositoryType","label":"Repository type","value":"file-repository"}`

Now trying to use this config:

```turtle
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>.
@prefix rep: <http://www.openrdf.org/config/repository#>.
@prefix sr: <http://www.openrdf.org/config/repository/sail#>.
@prefix sail: <http://www.openrdf.org/config/sail#>.
@prefix owlim: <http://www.ontotext.com/trree/owlim#>.
[] a rep:Repository ;
    rep:repositoryID "test-repo" ;
    rdfs:label "Test repo" ;
    rep:repositoryImpl [
        rep:repositoryType "file-repository" ;
    ].
```

Obviously this does not work (meanwhile the same config through the API worked).

This is really insane that we need to go through so much pain with so many not relevant error messages just to create a repo through the API. Please make up your mind on the repositoryType, I don't understand why we even need to set this, not setting anything should trigger a default, that should be the usual **triplestore** (SailRepository or file-repository or anything you call it), if people wants a Virtual KG they define it explicitly. That's really not hard to code.

What is a config that we can use to create a repository on GraphDB free edition through the API? Would it be possible to list the available repositoryType somewhere in the docs and fix all examples that are using `graphdb:SailRepository` since it is now unsupported? @nikolaykolev

**Comment by yaskoo** [comment]
`graphdb:SailRepository` was introduced in GraphDB v10 and since you are trying to use it in GraphDB v9.x you are getting the error message that it isn't supported.

The best way to get the correct sample configuration ttl file is to create it from the Workbench and then download the configuration:
![Screenshot from 2024-10-14 10-16-57](https://github.com/user-attachments/assets/c447226a-7373-4420-867c-a7e899eb636c)
