### ISSUE TITLE
Add image tag for OpenJDK 11 based image

### ISSUE THREAD

**Issue by erikgb** [Ontotext-AD/graphdb-docker#7]
With the release of GraphDB 9, [OpenJDK 11 is supported](http://graphdb.ontotext.com/documentation/standard/release-notes.html).

Java 11 has i.e. so much better memory management, and I am quite sure Open JDK 11 will be the preferred base image for the missing latest tag (ref #4 ). But for now it would be nice if Ontotext could push a OpenJDK 11 based image tag to [Docker Hub](https://hub.docker.com/r/ontotext/graphdb/tags).

I could prepare a PR if there is any chance of having it merged to master. I do not want to waste my time....

**Comment by nikolaykolev** [comment]
Just to let you know, by default GraphDB's official docker images use AdoptOpenJDK 11, starting from GraphDB 9.2.0
